<?php

/** @var $viewModel Task2\CurrentExchangeRate\ViewModel\ConfigProvider */

$viewModel = $block->getViewModel();
$var = $block->escapeHtml($viewModel->getTitle());
// $euro = $block->escapeHtml($viewModel->getEuro());

$btn = $block->escapeHtml($viewModel->getBtn());


?>
<!-- <h1><?= $block->escapeHtml($viewModel->getTitle()); ?></h1> -->

<div class="block block-content">
	<div class="box">
    	<div class="fieldset">
		 	<div class="minicart-wrapper" style="bottom: 25px;  right:15px">
			   	<div class="content-button">
			   		<h5 style="margin-bottom: 2px; text-align: center; color: #2297F9">Current exchange rate</h5>

			   		<!-- <form method="post" > -->
      				<input type="number" name="num" id="num"  maxlength="5" placeholder="0.0" 
                           style="width: 52px;
							    height: 22px;"
							value="" 
                    />
			        <span >
			        	<button type="submit" name="euro" id="euro"class="button-adapted">€</button>
					</span>
      				<span >
			        	<button type="submit" name="dollar" id="dollar" class="button-adapted">$</button>
					</span>

                    <input type="number" name="res" id="res" maxlength="5"
                           style="width: 52px;
							    height: 22px;"  
							value="<?php echo $var ?>" 
                    />
					<!-- </form> -->
                </div>
			</div>
		</div>
	</div>
</div>

<style>
.content-button{
	display: block;
}	
.button-adapted{
		background: white;
	    padding-left: 8px;
	    padding-right: 8px;
	    margin-bottom: 3px;
	    padding-bottom: 2px;
	    padding-top: 2px;
	    width: 26px;
	    color: #2297F9;
}
</style>