<?php
/* @var FaqVendor\Faq\Block\FaqQues $block */
?>

<form method="post" action="<?= $block->getQuestionUrl() ?>">
    <fieldset>

        <div class="input-group">
            <label for="question"><?= __("Do you have an important question? tell us!") ?>
                <input type="text" name="question" id="question" />
                <div class="input-group-append">
                    <input type="submit" value="<?= __("Send") ?>" />
                </div>
        </div>
    </fieldset>
</form>
